// Code generated by MockGen. DO NOT EDIT.
// Source: notification_service/internal/kafka (interfaces: NotificationProducerInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "notification_service/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotificationProducerInterface is a mock of NotificationProducerInterface interface.
type MockNotificationProducerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationProducerInterfaceMockRecorder
}

// MockNotificationProducerInterfaceMockRecorder is the mock recorder for MockNotificationProducerInterface.
type MockNotificationProducerInterfaceMockRecorder struct {
	mock *MockNotificationProducerInterface
}

// NewMockNotificationProducerInterface creates a new mock instance.
func NewMockNotificationProducerInterface(ctrl *gomock.Controller) *MockNotificationProducerInterface {
	mock := &MockNotificationProducerInterface{ctrl: ctrl}
	mock.recorder = &MockNotificationProducerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationProducerInterface) EXPECT() *MockNotificationProducerInterfaceMockRecorder {
	return m.recorder
}

// SendNotification mocks base method.
func (m *MockNotificationProducerInterface) SendNotification(arg0 context.Context, arg1 *models.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockNotificationProducerInterfaceMockRecorder) SendNotification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockNotificationProducerInterface)(nil).SendNotification), arg0, arg1)
}
