// Code generated by MockGen. DO NOT EDIT.
// Source: notification_service/internal/services/notifications (interfaces: NotificationStorage)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "notification_service/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotificationStorage is a mock of NotificationStorage interface.
type MockNotificationStorage struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationStorageMockRecorder
}

// MockNotificationStorageMockRecorder is the mock recorder for MockNotificationStorage.
type MockNotificationStorageMockRecorder struct {
	mock *MockNotificationStorage
}

// NewMockNotificationStorage creates a new mock instance.
func NewMockNotificationStorage(ctrl *gomock.Controller) *MockNotificationStorage {
	mock := &MockNotificationStorage{ctrl: ctrl}
	mock.recorder = &MockNotificationStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationStorage) EXPECT() *MockNotificationStorageMockRecorder {
	return m.recorder
}

// AddNotification mocks base method.
func (m *MockNotificationStorage) AddNotification(arg0 context.Context, arg1 *models.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNotification indicates an expected call of AddNotification.
func (mr *MockNotificationStorageMockRecorder) AddNotification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNotification", reflect.TypeOf((*MockNotificationStorage)(nil).AddNotification), arg0, arg1)
}

// GetNotificationStatusByIDs mocks base method.
func (m *MockNotificationStorage) GetNotificationStatusByIDs(arg0 context.Context, arg1 []string) ([]*models.NotificationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationStatusByIDs", arg0, arg1)
	ret0, _ := ret[0].([]*models.NotificationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationStatusByIDs indicates an expected call of GetNotificationStatusByIDs.
func (mr *MockNotificationStorageMockRecorder) GetNotificationStatusByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationStatusByIDs", reflect.TypeOf((*MockNotificationStorage)(nil).GetNotificationStatusByIDs), arg0, arg1)
}

// UpdateNotificationStatus mocks base method.
func (m *MockNotificationStorage) UpdateNotificationStatus(arg0 context.Context, arg1 []*models.NotificationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationStatus indicates an expected call of UpdateNotificationStatus.
func (mr *MockNotificationStorageMockRecorder) UpdateNotificationStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationStatus", reflect.TypeOf((*MockNotificationStorage)(nil).UpdateNotificationStatus), arg0, arg1)
}
