// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "notification_service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NotificationStorage is an autogenerated mock type for the NotificationStorage type
type NotificationStorage struct {
	mock.Mock
}

// GetNotificationStatusByIDs provides a mock function with given fields: ctx, IDs
func (_m *NotificationStorage) GetNotificationStatusByIDs(ctx context.Context, IDs []string) ([]*models.NotificationStatus, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationStatusByIDs")
	}

	var r0 []*models.NotificationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*models.NotificationStatus, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*models.NotificationStatus); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.NotificationStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotificationStatus provides a mock function with given fields: ctx, statuses
func (_m *NotificationStorage) UpdateNotificationStatus(ctx context.Context, statuses []*models.NotificationStatus) error {
	ret := _m.Called(ctx, statuses)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.NotificationStatus) error); ok {
		r0 = rf(ctx, statuses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationStorage creates a new instance of NotificationStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationStorage {
	mock := &NotificationStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
