// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "notification_service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NotificationServiceInterface is an autogenerated mock type for the NotificationServiceInterface type
type NotificationServiceInterface struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, n
func (_m *NotificationServiceInterface) Handle(ctx context.Context, n *models.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationServiceInterface creates a new instance of NotificationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationServiceInterface {
	mock := &NotificationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
