// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "notification_service/internal/models"
)

// NotificationProducerInterface is an autogenerated mock type for the NotificationProducerInterface type
type NotificationProducerInterface struct {
	mock.Mock
}

// SendNotification provides a mock function with given fields: ctx, n
func (_m *NotificationProducerInterface) SendNotification(ctx context.Context, n *models.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for SendNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendNotificationStatus provides a mock function with given fields: ctx, status
func (_m *NotificationProducerInterface) SendNotificationStatus(ctx context.Context, status *models.NotificationStatus) error {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for SendNotificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.NotificationStatus) error); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationProducerInterface creates a new instance of NotificationProducerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationProducerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationProducerInterface {
	mock := &NotificationProducerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
